version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - gateway
      
  kafka:
    image: bitnami/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test1"
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
    networks:
      - gateway
  
  producer:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE_NAME: 'producer'
        CMD_PATH: 'cmd/producer'
    volumes:
      - .:/go/src/producer
    depends_on:
      - kafka
    restart: always
    networks:
      - gateway
    env_file:
     - ./.env

  consumer:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE_NAME: 'consumer'
        CMD_PATH: 'cmd/consumer'
    volumes:
      - .:/go/src/consumer
    depends_on:
      - kafka
      - producer
    restart: always
    networks:
      - gateway
    env_file:
     - ./.env

networks: 
  gateway:
    external: true